### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by 683723** [Nuro-dev/MooMoo.io-Scripts#7]
Do any of these not require you to press a key to open?

**Comment by NuroC** [comment]
most of the script on the `moomooforge` category do not require you a key to open.

The following scripts do not require a key:
- AutoHeal
- Chat bypass
- Forge Connect
- GameGrid Removal
- Gold bots
- Item counter
- Name Replacer
- New cyan color

The other scripts may require either using the mouse wheel or some keybinds.
